import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { Window } from "happy-dom";

import {
	createCatalogInfo,
	createDebugRows,
	createUsageRows,
} from "../src/options/data.js";
import "../lib/provider-catalog.generated.js";
import "../lib/core.js";

const core = globalThis.BilingualTranslatorCore;
const catalog = globalThis.BilingualTranslatorProviderCatalog;

function createEventHub() {
	const listeners = new Set();
	return {
		addListener(listener) {
			listeners.add(listener);
		},
		removeListener(listener) {
			listeners.delete(listener);
		},
		emit(...arguments_) {
			for (const listener of listeners) {
				listener(...arguments_);
			}
		},
	};
}

function createPort() {
	const onMessage = createEventHub();
	const onDisconnect = createEventHub();
	return {
		disconnected: false,
		messages: [],
		onDisconnect,
		onMessage,
		disconnect() {
			this.disconnected = true;
			onDisconnect.emit();
		},
		drop() {
			this.disconnected = true;
			onDisconnect.emit();
		},
		postMessage(message) {
			this.messages.push(structuredClone(message));
		},
	};
}

function exposeWindow(window) {
	const values = {
		CustomEvent: window.CustomEvent,
		Document: window.Document,
		Element: window.Element,
		Event: window.Event,
		HTMLElement: window.HTMLElement,
		HTMLInputElement: window.HTMLInputElement,
		HTMLSelectElement: window.HTMLSelectElement,
		MutationObserver: window.MutationObserver,
		Node: window.Node,
		SVGElement: window.SVGElement,
		document: window.document,
		getComputedStyle: window.getComputedStyle.bind(window),
		location: window.location,
		navigator: window.navigator,
		window,
	};
	const previous = new Map();
	for (const [name, value] of Object.entries(values)) {
		previous.set(name, Object.getOwnPropertyDescriptor(globalThis, name));
		Object.defineProperty(globalThis, name, {
			configurable: true,
			writable: true,
			value,
		});
	}
	return () => {
		for (const [name, descriptor] of previous) {
			if (descriptor) {
				Object.defineProperty(globalThis, name, descriptor);
			} else {
				delete globalThis[name];
			}
		}
	};
}

async function settle() {
	await Promise.resolve();
	await new Promise((resolve) => setTimeout(resolve, 0));
	await Promise.resolve();
}

async function waitFor(predicate, message) {
	for (let attempt = 0; attempt < 60; attempt += 1) {
		if (predicate()) {
			return;
		}
		await settle();
	}
	assert.fail(message);
}

function clickByText(document, selector, text) {
	const element = [...document.querySelectorAll(selector)].find((candidate) =>
		candidate.textContent.includes(text),
	);
	assert.ok(element, `Could not find ${selector} containing ${text}`);
	element.click();
	return element;
}

function inputValue(window, input, value) {
	input.value = value;
	input.dispatchEvent(new window.Event("input", { bubbles: true }));
}

test("options entry uses only local, precompiled extension assets", async () => {
	const [html, script, styles, manifestSource] = await Promise.all([
		readFile(new URL("../options.html", import.meta.url), "utf8"),
		readFile(new URL("../options.js", import.meta.url), "utf8"),
		readFile(new URL("../options.css", import.meta.url), "utf8"),
		readFile(new URL("../manifest.json", import.meta.url), "utf8"),
	]);
	const manifest = JSON.parse(manifestSource);
	const scriptSources = [...html.matchAll(/<script\s+src="([^"]+)"\s+defer><\/script>/gu)].map(
		(match) => match[1],
	);

	assert.deepEqual(scriptSources, [
		"lib/provider-catalog.generated.js",
		"lib/core.js",
		"options.js",
	]);
	assert.match(html, /<div id="app"><\/div>/u);
	assert.doesNotMatch(html, /<script(?!\s+src=)[^>]*>/u);
	assert.equal(manifest.options_ui.page, "options.html");
	assert.equal(manifest.options_ui.open_in_tab, true);
	assert.match(script, /^\/\/ Generated by scripts\/build-options\.mjs/u);
	assert.match(styles, /^\/\* Generated by scripts\/build-options\.mjs/u);
	assert.doesNotMatch(script, /\beval\s*\(/u);
	assert.doesNotMatch(script, /\bnew\s+Function\s*\(/u);
	assert.doesNotMatch(script, /\bimport\s*\(/u);
});

test("catalog, usage, and debug views keep local allowlists and safe fields", () => {
	const info = createCatalogInfo(catalog);
	assert.equal(info.error, "");
	assert.equal(info.sha, "14119152");
	assert.equal(info.models.deepseek[0].id, "deepseek-v4-flash");
	assert.match(info.models.deepseek[0].label, /输入 \$0\.14 \/ 输出 \$0\.28/u);

	const usage = createUsageRows(
		{
			"2026-08": {
				azure: { apiCalls: 1, billedCharacters: 18 },
				deepseek: { apiCalls: 2, inputTokens: 9, outputTokens: 4 },
			},
		},
		"2026-08",
		(id) => id.toUpperCase(),
	);
	assert.equal(usage[0].metrics.at(-1).label, "计费字符");
	assert.equal(usage[1].metrics.at(-1).value, "9 / 4");

	const [row] = createDebugRows([
		{
			seq: 7,
			timestamp: "2026-08-04T08:00:00.000Z",
			eventType: "<img src=x onerror=alert(1)>",
			apiHost: "https://user:secret@api.example.com/v1",
			endpoint: "https://api.example.com/v1/chat?api_key=secret#fragment",
			requestBody: "must-not-render",
		},
	]);
	assert.equal(row.name, "<img src=x onerror=alert(1)>");
	assert.ok(row.fields.some((field) => field.label === "API Host" && field.value === "api.example.com"));
	assert.ok(
		row.fields.some(
			(field) => field.label === "端点" && field.value === "https://api.example.com/v1/chat",
		),
	);
	assert.equal(row.fields.some((field) => field.value.includes("must-not-render")), false);
});

test("Vue options page preserves drafts, message order, debug safety, and DOM contracts", async () => {
	const window = new Window({ url: "chrome-extension://options-test/options.html" });
	const restoreWindow = exposeWindow(window);
	window.document.body.innerHTML = '<div id="app"></div>';
	const calls = [];
	const ports = [];
	const storageChanged = createEventHub();
	const nativeClearInterval = globalThis.clearInterval;
	const nativeSetInterval = globalThis.setInterval;
	const nativeSetTimeout = globalThis.setTimeout;
	let heartbeat;
	let heartbeatDelay;
	let reconnect;
	let settings = core.normalizeSettings({
		provider: "deepseek",
		deepseek: { apiKey: "deepseek-key", model: "deepseek-v4-flash" },
	});
	let debugEvents = [];
	const usage = {
		[core.getMonthKey()]: {
			deepseek: {
				apiCalls: 1,
				charactersSubmitted: 120,
				cachedCharacters: 40,
				inputTokens: 4,
				outputTokens: 2,
			},
		},
	};
	const chrome = {
		runtime: {
			connect() {
				const port = createPort();
				ports.push(port);
				return port;
			},
			getManifest() {
				return { version: "0.4.0" };
			},
			async sendMessage(message) {
				calls.push(structuredClone(message));
				switch (message.type) {
					case "GET_OPTIONS_STATE":
						return { ok: true, settings: structuredClone(settings), usage: structuredClone(usage) };
					case "SAVE_SETTINGS":
						settings = core.normalizeSettings(message.settings);
						return { ok: true, settings: structuredClone(settings) };
					case "TEST_PROVIDER":
						return { ok: true, message: "OpenAI 连接成功" };
					case "CLEAR_CACHE":
						return { ok: true, removed: 3 };
					case "GET_DEBUG_LOGS":
						return { ok: true, events: structuredClone(debugEvents) };
					case "CLEAR_DEBUG_LOGS":
						debugEvents = [];
						return { ok: true };
					default:
						return { ok: false, error: `unexpected message: ${message.type}` };
				}
			},
		},
		storage: { onChanged: storageChanged },
	};
	globalThis.chrome = chrome;

	try {
		await import(`../options.js?options-test=${Date.now()}`);
		await waitFor(
			() => window.document.querySelector("#settings-form"),
			"Vue options form did not mount",
		);

		const requiredIds = [
			"extension-version",
			"settings-form",
			"provider",
			"azure-api-key",
			"azure-region",
			"deepl-api-key",
			"deepseek-api-key",
			"deepseek-model",
			"openai-api-key",
			"openai-model",
			"google-api-key",
			"google-model",
			"anthropic-api-key",
			"anthropic-model",
			"catalog-status",
			"catalog-source-sha",
			"catalog-fetched-at",
			"target-mode",
			"concurrency",
			"translate-dynamic",
			"debug-logging",
			"debug-connection",
			"clear-debug-logs",
			"debug-events",
			"save",
			"test-provider",
			"status",
			"clear-cache",
			"usage",
		];
		for (const id of requiredIds) {
			assert.ok(window.document.getElementById(id), `Missing options DOM anchor #${id}`);
		}
		assert.equal(window.document.querySelectorAll("[data-provider-panel]").length, 6);
		assert.equal(window.document.querySelector('[data-provider-panel="deepseek"]').hidden, false);
		assert.equal(window.document.querySelector('[data-provider-panel="openai"]').hidden, true);
		assert.equal(window.document.querySelector("#extension-version").textContent, "v0.4.0");
		assert.match(window.document.querySelector("#usage").textContent, /4 \/ 2/u);

		clickByText(window.document, ".provider-choice", "OpenAI");
		await settle();
		assert.equal(window.document.querySelector('[data-provider-panel="openai"]').hidden, false);
		const openAiKey = window.document.querySelector("#openai-api-key");
		inputValue(window, openAiKey, "openai-draft-key");
		clickByText(window.document, ".provider-choice", "DeepSeek");
		clickByText(window.document, ".provider-choice", "OpenAI");
		await settle();
		assert.equal(openAiKey.value, "openai-draft-key");

		calls.length = 0;
		window.document.querySelector("#test-provider").click();
		await waitFor(
			() => window.document.querySelector("#status").textContent.includes("连接成功"),
			"Provider test did not finish",
		);
		assert.deepEqual(
			calls.map((message) => message.type),
			["SAVE_SETTINGS", "TEST_PROVIDER", "GET_OPTIONS_STATE"],
		);
		assert.equal(calls[0].settings.openai.apiKey, "openai-draft-key");

		calls.length = 0;
		globalThis.setInterval = (callback, delay) => {
			heartbeat = callback;
			heartbeatDelay = delay;
			return 101;
		};
		globalThis.clearInterval = () => {};
		const debugToggle = window.document.querySelector("#debug-logging");
		debugToggle.checked = true;
		debugToggle.dispatchEvent(new window.Event("change", { bubbles: true }));
		await waitFor(() => ports.length === 1, "Debug port did not connect");
		assert.ok(calls.some((message) => message.type === "GET_DEBUG_LOGS"));
		assert.match(window.document.querySelector("#debug-connection").textContent, /保存设置后/u);
		assert.equal(heartbeatDelay, 20_000);
		heartbeat();
		assert.deepEqual(ports[0].messages, [{ type: "DEBUG_PING" }]);

		globalThis.setTimeout = (callback, delay, ...arguments_) => {
			if (delay === 1_000) {
				reconnect = callback;
				return 102;
			}
			return nativeSetTimeout(callback, delay, ...arguments_);
		};
		ports[0].drop();
		assert.equal(typeof reconnect, "function");
		reconnect();
		await settle();
		assert.equal(ports.length, 2);
		const activePort = ports.at(-1);

		activePort.onMessage.emit({
			type: "DEBUG_SNAPSHOT",
			events: [
				{
					seq: 1,
					timestamp: "2026-08-04T08:00:00.000Z",
					eventType: "<img src=x onerror=alert(1)>",
					endpoint: "https://api.example.com/v1/chat?api_key=secret",
					requestBody: "must-not-render",
				},
			],
		});
		await settle();
		assert.equal(
			window.document.querySelector(".debug-event-name").textContent,
			"<img src=x onerror=alert(1)>",
		);
		assert.equal(window.document.querySelector("#debug-events img"), null);
		assert.match(window.document.querySelector(".debug-event-meta").textContent, /https:\/\/api\.example\.com\/v1\/chat/u);
		assert.doesNotMatch(window.document.querySelector("#debug-events").textContent, /must-not-render/u);

		activePort.onMessage.emit({
			type: "DEBUG_SNAPSHOT",
			events: Array.from({ length: 301 }, (_, index) => ({
				seq: index + 1,
				timestamp: "2026-08-04T08:00:00.000Z",
				eventType: "request-end",
			})),
		});
		await settle();
		assert.equal(window.document.querySelectorAll(".debug-event").length, 300);

		const providerBeforeStorageEvent = [...window.document.querySelectorAll(".provider-choice")].find(
			(button) => button.getAttribute("aria-checked") === "true",
		).textContent;
		storageChanged.emit(
			{
				[core.SETTINGS_KEY]: {
					newValue: core.normalizeSettings({
						provider: "deepseek",
						debugLogging: true,
						deepseek: { apiKey: "stored-key", model: "deepseek-v4-flash" },
					}),
				},
			},
			"local",
		);
		await settle();
		const providerAfterStorageEvent = [...window.document.querySelectorAll(".provider-choice")].find(
			(button) => button.getAttribute("aria-checked") === "true",
		).textContent;
		assert.equal(providerAfterStorageEvent, providerBeforeStorageEvent);
		assert.equal(debugToggle.checked, true);

		window.dispatchEvent(new window.Event("beforeunload"));
		assert.equal(activePort.disconnected, true);
	} finally {
		globalThis.clearInterval = nativeClearInterval;
		globalThis.setInterval = nativeSetInterval;
		globalThis.setTimeout = nativeSetTimeout;
		delete globalThis.chrome;
		restoreWindow();
		window.close();
	}
});
