import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import { Window } from "happy-dom";

import {
	createCatalogInfo,
	createDebugRequests,
	createDebugRows,
	createUsageRows,
} from "../src/options/data.js";
import "../chrome-extension/generated/provider-catalog.js";
import "../chrome-extension/shared/core.js";

const core = globalThis.BilingualTranslatorCore;
const catalog = globalThis.BilingualTranslatorProviderCatalog;

function createEventHub() {
	const listeners = new Set();
	return {
		addListener(listener) {
			listeners.add(listener);
		},
		removeListener(listener) {
			listeners.delete(listener);
		},
		emit(...arguments_) {
			for (const listener of listeners) {
				listener(...arguments_);
			}
		},
	};
}

function createPort() {
	const onMessage = createEventHub();
	const onDisconnect = createEventHub();
	return {
		disconnected: false,
		messages: [],
		onDisconnect,
		onMessage,
		disconnect() {
			this.disconnected = true;
			onDisconnect.emit();
		},
		drop() {
			this.disconnected = true;
			onDisconnect.emit();
		},
		postMessage(message) {
			this.messages.push(structuredClone(message));
		},
	};
}

function exposeWindow(window) {
	const values = {
		CustomEvent: window.CustomEvent,
		Document: window.Document,
		Element: window.Element,
		Event: window.Event,
		HTMLElement: window.HTMLElement,
		HTMLInputElement: window.HTMLInputElement,
		HTMLSelectElement: window.HTMLSelectElement,
		MutationObserver: window.MutationObserver,
		Node: window.Node,
		SVGElement: window.SVGElement,
		document: window.document,
		getComputedStyle: window.getComputedStyle.bind(window),
		location: window.location,
		navigator: window.navigator,
		window,
	};
	const previous = new Map();
	for (const [name, value] of Object.entries(values)) {
		previous.set(name, Object.getOwnPropertyDescriptor(globalThis, name));
		Object.defineProperty(globalThis, name, {
			configurable: true,
			writable: true,
			value,
		});
	}
	return () => {
		for (const [name, descriptor] of previous) {
			if (descriptor) {
				Object.defineProperty(globalThis, name, descriptor);
			} else {
				delete globalThis[name];
			}
		}
	};
}

async function settle() {
	await Promise.resolve();
	await new Promise((resolve) => setTimeout(resolve, 0));
	await Promise.resolve();
}

async function waitFor(predicate, message) {
	for (let attempt = 0; attempt < 60; attempt += 1) {
		if (predicate()) {
			return;
		}
		await settle();
	}
	assert.fail(message);
}

function clickByText(document, selector, text) {
	const element = [...document.querySelectorAll(selector)].find((candidate) =>
		candidate.textContent.includes(text),
	);
	assert.ok(element, `Could not find ${selector} containing ${text}`);
	element.click();
	return element;
}

function inputValue(window, input, value) {
	input.value = value;
	input.dispatchEvent(new window.Event("input", { bubbles: true }));
}

function selectValue(window, select, value) {
	select.value = value;
	select.dispatchEvent(new window.Event("change", { bubbles: true }));
}

function chooseProvider(window, document, providerId) {
	const input = document.querySelector(`#provider-${providerId}`);
	assert.ok(input, `Could not find Provider ${providerId}`);
	input.checked = true;
	input.dispatchEvent(new window.Event("change", { bubbles: true }));
}

test("options entry uses only local, precompiled extension assets", async () => {
	const [html, script, styles, manifestSource] = await Promise.all([
		readFile(new URL("../chrome-extension/options/index.html", import.meta.url), "utf8"),
		readFile(new URL("../chrome-extension/options/options.js", import.meta.url), "utf8"),
		readFile(new URL("../chrome-extension/options/options.css", import.meta.url), "utf8"),
		readFile(new URL("../chrome-extension/manifest.json", import.meta.url), "utf8"),
	]);
	const manifest = JSON.parse(manifestSource);
	const scriptSources = [...html.matchAll(/<script\s+src="([^"]+)"\s+defer><\/script>/gu)].map(
		(match) => match[1],
	);

	assert.deepEqual(scriptSources, [
		"../generated/provider-catalog.js",
		"../shared/core.js",
		"options.js",
	]);
	assert.match(html, /<div id="app"><\/div>/u);
	assert.doesNotMatch(html, /<script(?!\s+src=)[^>]*>/u);
	assert.equal(manifest.options_ui.page, "options/index.html");
	assert.equal(manifest.options_ui.open_in_tab, true);
	assert.match(script, /^\/\/ Generated by scripts\/build-options\.mjs/u);
	assert.match(styles, /^\/\* Generated by scripts\/build-options\.mjs/u);
	assert.doesNotMatch(script, /\beval\s*\(/u);
	assert.doesNotMatch(script, /\bnew\s+Function\s*\(/u);
	assert.doesNotMatch(script, /\bimport\s*\(/u);
});

test("catalog, usage, and debug views keep local allowlists and safe fields", () => {
	const info = createCatalogInfo(catalog);
	assert.equal(info.error, "");
	assert.equal(info.sha, "14119152");
	assert.equal(info.models.deepseek[0].id, "deepseek-v4-flash");
	assert.match(info.models.deepseek[0].label, /\$0\.14 \/ \$0\.28/u);
	assert.equal(info.models.deepseek[0].optionLabel, "DeepSeek V4 Flash");
	assert.equal(info.models.deepseek[0].costText, "$0.14 / $0.28");

	const usage = createUsageRows(
		{
			"2026-08": {
				azure: { apiCalls: 1, billedCharacters: 18 },
				deepseek: { apiCalls: 2, inputTokens: 9, outputTokens: 4 },
			},
		},
		"2026-08",
		(id) => id.toUpperCase(),
	);
	assert.equal(usage[0].metrics.at(-1).label, "计费字符");
	assert.equal(usage[1].metrics.at(-1).value, "9 / 4");

	const [row] = createDebugRows([
		{
			seq: 7,
			timestamp: "2026-08-04T08:00:00.000Z",
			eventType: "<img src=x onerror=alert(1)>",
			apiHost: "https://user:secret@api.example.com/v1",
			endpoint: "https://api.example.com/v1/chat?api_key=secret#fragment",
			requestBody: "must-not-render",
		},
	]);
	assert.equal(row.name, "<img src=x onerror=alert(1)>");
	assert.ok(row.fields.some((field) => field.label === "API Host" && field.value === "api.example.com"));
	assert.ok(
		row.fields.some(
			(field) => field.label === "端点" && field.value === "https://api.example.com/v1/chat",
		),
	);
	assert.equal(row.fields.some((field) => field.value.includes("must-not-render")), false);

	const [request] = createDebugRequests([
		{
			seq: 8,
			timestamp: "2026-08-04T08:00:01.000Z",
			eventType: "sdk.request-start",
			requestId: "provider-request-1",
			attempt: 1,
			provider: "deepseek",
			model: "deepseek-v4-flash",
			method: "POST",
			endpoint: "https://api.example.com/v1/chat?api_key=secret",
			status: "started",
		},
		{
			seq: 9,
			timestamp: "2026-08-04T08:00:01.052Z",
			eventType: "sdk.request-end",
			requestId: "provider-request-1",
			attempt: 1,
			method: "POST",
			endpoint: "https://api.example.com/v1/chat?api_key=secret",
			httpStatus: 401,
			elapsedMs: 52,
			errorCode: "http_401",
			status: "error",
		},
	]);
	assert.equal(request.name, "POST api.example.com");
	assert.equal(request.badge, "HTTP 401");
	assert.equal(request.status, "error");
	assert.match(request.code, /sdk\.request-start → sdk\.request-end/u);
	assert.ok(
		request.fields.some(
			(field) => field.label === "端点" && field.value === "https://api.example.com/v1/chat",
		),
	);
	assert.doesNotMatch(request.searchText, /api_key=secret/u);
});

test("Vue options page keeps the shortest setup path, drafts, debug safety, and message order", async () => {
	const window = new Window({ url: "chrome-extension://options-test/options/index.html" });
	let copiedDebugText = "";
	Object.defineProperty(window.navigator, "clipboard", {
		configurable: true,
		value: {
			async writeText(value) {
				copiedDebugText = value;
			},
		},
	});
	const restoreWindow = exposeWindow(window);
	window.document.body.innerHTML = '<div id="app"></div>';
	const calls = [];
	const ports = [];
	const storageChanged = createEventHub();
	const nativeClearInterval = globalThis.clearInterval;
	const nativeSetInterval = globalThis.setInterval;
	const nativeSetTimeout = globalThis.setTimeout;
	let heartbeat;
	let heartbeatDelay;
	let reconnect;
	let settings = core.normalizeSettings({
		provider: "deepseek",
		deepseek: { apiKey: "deepseek-key", model: "deepseek-v4-flash" },
	});
	let debugEvents = [];
	const usage = {
		[core.getMonthKey()]: {
			deepseek: {
				apiCalls: 1,
				charactersSubmitted: 120,
				cachedCharacters: 40,
				inputTokens: 4,
				outputTokens: 2,
			},
		},
	};
	const chrome = {
		runtime: {
			connect() {
				const port = createPort();
				ports.push(port);
				return port;
			},
			getManifest() {
				return { version: "0.4.0" };
			},
			async sendMessage(message) {
				calls.push(structuredClone(message));
				switch (message.type) {
					case "GET_OPTIONS_STATE":
						return { ok: true, settings: structuredClone(settings), usage: structuredClone(usage) };
					case "SAVE_SETTINGS":
						settings = core.normalizeSettings(message.settings);
						return { ok: true, settings: structuredClone(settings) };
					case "SET_DEBUG_LOGGING":
						settings = core.normalizeSettings({
							...settings,
							debugLogging: message.enabled,
						});
						return { ok: true, debugLogging: settings.debugLogging };
					case "TEST_PROVIDER":
						return { ok: true, message: "OpenAI 连接成功" };
					case "CLEAR_CACHE":
						return { ok: true, removed: 3 };
					case "GET_DEBUG_LOGS":
						return { ok: true, events: structuredClone(debugEvents) };
					case "CLEAR_DEBUG_LOGS":
						debugEvents = [];
						return { ok: true };
					default:
						return { ok: false, error: `unexpected message: ${message.type}` };
				}
			},
		},
		storage: { onChanged: storageChanged },
	};
	globalThis.chrome = chrome;

	try {
		await import(`../chrome-extension/options/options.js?options-test=${Date.now()}`);
		await waitFor(
			() => window.document.querySelector("#settings-form"),
			"Vue options form did not mount",
		);

		const requiredIds = [
			"extension-version",
			"settings-form",
			"provider",
			"deepseek-api-key",
			"deepseek-model",
			"catalog-status",
			"catalog-source-sha",
			"catalog-fetched-at",
			"target-mode",
			"concurrency",
			"translate-dynamic",
			"test-provider",
			"status",
			"clear-cache",
			"usage",
		];
		for (const id of requiredIds) {
			assert.ok(window.document.getElementById(id), `Missing options DOM anchor #${id}`);
		}
		assert.equal(window.document.querySelectorAll("[data-provider-fields]").length, 1);
		assert.ok(window.document.querySelector('[data-provider-fields="deepseek"]'));
		assert.equal(window.document.querySelector('input[name="provider"]:checked').value, "deepseek");
		assert.equal(window.document.querySelectorAll("#provider > .provider-grid:first-of-type .provider-choice").length, 3);
		assert.equal(window.document.querySelector("#provider-more").getAttribute("aria-expanded"), "false");
		assert.equal(window.document.querySelector("#provider-more-options").style.display, "none");
		assert.equal(window.document.querySelectorAll(".primary").length, 1);
		assert.equal(window.document.querySelector("#save"), null);
		assert.equal(window.document.querySelector("#test-provider").textContent.trim(), "保存并测试");
		assert.equal(window.document.querySelector("#extension-version").textContent, "v0.4.0");
		assert.match(window.document.querySelector("#usage").textContent, /4 \/ 2/u);

		chooseProvider(window, window.document, "openai");
		await settle();
		assert.ok(window.document.querySelector('[data-provider-fields="openai"]'));
		const openAiKey = window.document.querySelector("#openai-api-key");
		inputValue(window, openAiKey, "openai-draft-key");
		chooseProvider(window, window.document, "deepseek");
		chooseProvider(window, window.document, "openai");
		await settle();
		assert.equal(window.document.querySelector("#openai-api-key").value, "openai-draft-key");

		window.document.querySelector("#provider-more").click();
		await settle();
		assert.equal(window.document.querySelector("#provider-more").getAttribute("aria-expanded"), "true");
		assert.notEqual(window.document.querySelector("#provider-more-options").style.display, "none");
		chooseProvider(window, window.document, "anthropic");
		await settle();
		assert.ok(window.document.querySelector('[data-provider-fields="anthropic"]'));
		chooseProvider(window, window.document, "openai");
		await settle();

		calls.length = 0;
		window.document.querySelector("#test-provider").click();
		await waitFor(
			() => window.document.querySelector("#status").textContent.includes("连接成功"),
			"Provider test did not finish",
		);
		assert.deepEqual(
			calls.map((message) => message.type),
			["SAVE_SETTINGS", "TEST_PROVIDER", "GET_OPTIONS_STATE"],
		);
		assert.equal(calls[0].settings.openai.apiKey, "openai-draft-key");
		assert.match(window.document.querySelector(".connected").textContent, /连接可用/u);

		calls.length = 0;
		clickByText(window.document, ".tabs button", "调试");
		await settle();
		assert.equal(window.location.hash, "#debug");
		for (const id of [
			"debug-test-provider",
			"debug-logging",
			"debug-connection",
			"copy-debug-logs",
			"clear-debug-logs",
			"debug-events",
		]) {
			assert.ok(window.document.getElementById(id), `Missing debug DOM anchor #${id}`);
		}
		globalThis.setInterval = (callback, delay) => {
			heartbeat = callback;
			heartbeatDelay = delay;
			return 101;
		};
		globalThis.clearInterval = () => {};
		const debugToggle = window.document.querySelector("#debug-logging");
		debugToggle.checked = true;
		debugToggle.dispatchEvent(new window.Event("change", { bubbles: true }));
		await waitFor(() => ports.length === 1, "Debug port did not connect");
		await waitFor(
			() => calls.some((message) => message.type === "SET_DEBUG_LOGGING"),
			"Debug preference was not saved independently",
		);
		assert.equal(
			calls.filter((message) => message.type === "SET_DEBUG_LOGGING").at(-1).enabled,
			true,
		);
		assert.equal(calls.some((message) => message.type === "SAVE_SETTINGS"), false);
		assert.equal(settings.openai.apiKey, "openai-draft-key");
		assert.ok(calls.some((message) => message.type === "GET_DEBUG_LOGS"));
		assert.match(window.document.querySelector("#debug-connection").textContent, /实时调试已连接/u);
		assert.equal(heartbeatDelay, 20_000);
		heartbeat();
		assert.deepEqual(ports[0].messages, [{ type: "DEBUG_PING" }]);

		globalThis.setTimeout = (callback, delay, ...arguments_) => {
			if (delay === 1_000) {
				reconnect = callback;
				return 102;
			}
			return nativeSetTimeout(callback, delay, ...arguments_);
		};
		ports[0].drop();
		assert.equal(typeof reconnect, "function");
		reconnect();
		await settle();
		assert.equal(ports.length, 2);
		const activePort = ports.at(-1);

		activePort.onMessage.emit({
			type: "DEBUG_SNAPSHOT",
			events: [
				{
					seq: 1,
					timestamp: "2026-08-04T08:00:00.000Z",
					eventType: "<img src=x onerror=alert(1)>",
					endpoint: "https://api.example.com/v1/chat?api_key=secret",
					requestBody: "must-not-render",
				},
			],
		});
		await settle();
		clickByText(window.document, ".debug-modes button", "全部事件");
		await settle();
		assert.equal(
			window.document.querySelector(".debug-event-name").textContent,
			"<img src=x onerror=alert(1)>",
		);
		assert.equal(window.document.querySelector("#debug-events img"), null);
		assert.match(window.document.querySelector(".debug-event-meta").textContent, /https:\/\/api\.example\.com\/v1\/chat/u);
		assert.doesNotMatch(window.document.querySelector("#debug-events").textContent, /must-not-render/u);
		window.document.querySelector("#copy-debug-logs").click();
		await settle();
		assert.match(copiedDebugText, /https:\/\/api\.example\.com\/v1\/chat/u);
		assert.doesNotMatch(copiedDebugText, /api_key=secret|must-not-render/u);

		activePort.onMessage.emit({
			type: "DEBUG_SNAPSHOT",
			events: Array.from({ length: 301 }, (_, index) => ({
				seq: index + 1,
				timestamp: "2026-08-04T08:00:00.000Z",
				eventType: "request-end",
			})),
		});
		await settle();
		assert.equal(window.document.querySelectorAll(".debug-event").length, 300);

		clickByText(window.document, ".tabs button", "配置");
		await settle();
		assert.equal(window.location.hash, "#setup");
		const providerBeforeStorageEvent = window.document.querySelector('input[name="provider"]:checked').value;
		storageChanged.emit(
			{
				[core.SETTINGS_KEY]: {
					newValue: core.normalizeSettings({
						provider: "deepseek",
						debugLogging: true,
						deepseek: { apiKey: "stored-key", model: "deepseek-v4-flash" },
					}),
				},
			},
			"local",
		);
		await settle();
		const providerAfterStorageEvent = window.document.querySelector('input[name="provider"]:checked').value;
		assert.equal(providerAfterStorageEvent, providerBeforeStorageEvent);
		assert.equal(settings.debugLogging, true);

		window.dispatchEvent(new window.Event("beforeunload"));
		assert.equal(activePort.disconnected, true);
	} finally {
		globalThis.clearInterval = nativeClearInterval;
		globalThis.setInterval = nativeSetInterval;
		globalThis.setTimeout = nativeSetTimeout;
		delete globalThis.chrome;
		restoreWindow();
		window.close();
	}
});
