import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const extensionDirectory = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repositoryDirectory = resolve(extensionDirectory, "..");
const outputPath = resolve(extensionDirectory, "src/generated/provider-catalog.ts");
const checkOnly = process.argv.includes("--check");

const [catalog, allowlist] = await Promise.all([
	readJson(resolve(repositoryDirectory, "data/models-dev-subset.json")),
	readJson(resolve(repositoryDirectory, "config/provider-allowlist.json")),
]);

const catalogProviders = new Map(catalog.providers.map((provider) => [provider.id, provider]));
const generatedProviders = allowlist.providers.map((allowedProvider) => {
	const provider = catalogProviders.get(allowedProvider.id);
	if (!provider) {
		throw new Error(`Provider ${allowedProvider.id} is missing from the fixed model snapshot.`);
	}

	const model = provider.models.find(
		(candidate) => candidate.id === allowedProvider.defaultModelId,
	);
	if (!model) {
		throw new Error(
			`Model ${allowedProvider.defaultModelId} is missing from provider ${allowedProvider.id}.`,
		);
	}

	return {
		id: allowedProvider.id,
		name: provider.name,
		sdkPackage: allowedProvider.sdkPackage,
		apiBaseURL: allowedProvider.apiBaseURL,
		defaultModelId: allowedProvider.defaultModelId,
		modelName: model.name,
		cost: {
			input: model.cost.input,
			output: model.cost.output,
			...(model.cost.reasoning === undefined ? {} : { reasoning: model.cost.reasoning }),
			...(model.cost.cacheRead === undefined ? {} : { cacheRead: model.cost.cacheRead }),
			...(model.cost.cacheWrite === undefined ? {} : { cacheWrite: model.cost.cacheWrite }),
		},
		capabilities: {
			reasoning: model.capabilities.reasoning,
			temperature: model.capabilities.temperature,
		},
	};
});

if (!generatedProviders.some((provider) => provider.id === allowlist.defaultProviderId)) {
	throw new Error(`Default provider ${allowlist.defaultProviderId} is not allowlisted.`);
}

const source = `// Generated by scripts/sync-catalog.mjs. Do not edit directly.

export type ModelProviderId = ${generatedProviders.map((provider) => JSON.stringify(provider.id)).join(" | ")};
export type ProviderId = "azure" | "deepl" | ModelProviderId;

export interface ModelCatalogEntry {
\tid: ModelProviderId;
\tname: string;
\tsdkPackage: string;
\tapiBaseURL: string;
\tdefaultModelId: string;
\tmodelName: string;
\tcost: {
\t\tinput: number;
\t\toutput: number;
\t\treasoning?: number;
\t\tcacheRead?: number;
\t\tcacheWrite?: number;
\t};
\tcapabilities: {
\t\treasoning: boolean;
\t\ttemperature: boolean;
\t};
}

export const SNAPSHOT = ${JSON.stringify(catalog.source, null, "\t")} as const;

export const DEFAULT_PROVIDER_ID = ${JSON.stringify(allowlist.defaultProviderId)} as const;

export const PROVIDER_IDS = ["azure", "deepl", ${generatedProviders.map((provider) => JSON.stringify(provider.id)).join(", ")}] as const satisfies readonly ProviderId[];

export const MODEL_PROVIDERS = ${JSON.stringify(generatedProviders, null, "\t")} as const satisfies readonly ModelCatalogEntry[];
`;

if (checkOnly) {
	let currentSource;
	try {
		currentSource = await readFile(outputPath, "utf8");
	} catch (error) {
		if (error instanceof Error && "code" in error && error.code === "ENOENT") {
			throw new Error("Raycast provider catalog is missing. Run npm run sync:catalog.");
		}
		throw error;
	}

	if (currentSource !== source) {
		throw new Error("Raycast provider catalog is stale. Run npm run sync:catalog.");
	}
	console.log("Raycast provider catalog is current.");
} else {
	await writeFile(outputPath, source, "utf8");
	console.log(`Generated ${outputPath}`);
}

async function readJson(path) {
	return JSON.parse(await readFile(path, "utf8"));
}
