import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

import {
	assertNoExternalImports,
	assertSafeJavaScript,
	collectBundleOutputs,
	parseBuildArguments,
	writeOrCheckOutputs,
} from "./build-outputs.mjs";
import { createVueSfcPlugin } from "./vue-sfc-plugin.mjs";

const applicationRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourceDirectory = resolve(applicationRoot, "src/options");
const outputDirectory = resolve(applicationRoot, "chrome-extension/options");
const expectedPaths = [
	resolve(outputDirectory, "options.js"),
	resolve(outputDirectory, "options.css"),
];
const { checkOnly } = parseBuildArguments("build-options.mjs");

const bundle = await build({
	absWorkingDir: applicationRoot,
	banner: {
		css: "/* Generated by scripts/build-options.mjs. Do not edit. */",
		js: "// Generated by scripts/build-options.mjs. Do not edit.",
	},
	bundle: true,
	charset: "utf8",
	define: {
		"process.env.NODE_ENV": '"production"',
		__VUE_OPTIONS_API__: "false",
		__VUE_PROD_DEVTOOLS__: "false",
		__VUE_PROD_HYDRATION_MISMATCH_DETAILS__: "false",
	},
	entryPoints: [{ in: "src/options/main.js", out: "options" }],
	format: "iife",
	legalComments: "eof",
	logLevel: "warning",
	metafile: true,
	minify: true,
	outdir: outputDirectory,
	packages: "bundle",
	platform: "browser",
	plugins: [createVueSfcPlugin({ applicationRoot, sourceDirectory })],
	sourcemap: false,
	splitting: false,
	target: "chrome140",
	treeShaking: true,
	write: false,
});

assertNoExternalImports(bundle.metafile, "Options");
const outputs = collectBundleOutputs(bundle.outputFiles, expectedPaths, "options");
assertSafeJavaScript(outputs.get(resolve(outputDirectory, "options.js")).toString("utf8"), "options.js");
await writeOrCheckOutputs(outputs, { checkOnly, buildCommand: "npm run build:options" });

console.log(
	checkOnly
		? "Generated options.js and options.css are up to date."
		: "Generated options.js and options.css.",
);
