import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

import {
	assertNoExternalImports,
	assertSafeJavaScript,
	collectBundleOutputs,
	parseBuildArguments,
	writeOrCheckOutputs,
} from "./build-outputs.mjs";

const applicationRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputDirectory = resolve(applicationRoot, "chrome-extension/popup");
const expectedPaths = [
	resolve(outputDirectory, "popup.js"),
	resolve(outputDirectory, "popup.css"),
];
const { checkOnly } = parseBuildArguments("build-popup.mjs");

const bundle = await build({
	absWorkingDir: applicationRoot,
	banner: {
		css: "/* Generated by scripts/build-popup.mjs. Do not edit. */",
		js: "// Generated by scripts/build-popup.mjs. Do not edit.",
	},
	bundle: true,
	charset: "utf8",
	entryPoints: [{ in: "src/popup/main.js", out: "popup" }],
	format: "iife",
	legalComments: "eof",
	logLevel: "warning",
	metafile: true,
	minify: true,
	outdir: outputDirectory,
	platform: "browser",
	sourcemap: false,
	target: "chrome140",
	treeShaking: true,
	write: false,
});

assertNoExternalImports(bundle.metafile, "Popup");
const outputs = collectBundleOutputs(bundle.outputFiles, expectedPaths, "popup");
assertSafeJavaScript(outputs.get(resolve(outputDirectory, "popup.js")).toString("utf8"), "popup.js");
await writeOrCheckOutputs(outputs, { checkOnly, buildCommand: "npm run build:popup" });

console.log(
	checkOnly
		? "Generated popup.js and popup.css are up to date."
		: "Generated popup.js and popup.css.",
);
