import { copyFile, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { crc32, deflateSync } from "node:zlib";

const cliArguments = process.argv.slice(2);
if (cliArguments.length !== 0 && (cliArguments.length !== 2 || cliArguments[0] !== "--output-dir")) {
	throw new Error("Usage: node scripts/export-icons.mjs [--output-dir <directory>]");
}
const applicationRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourceDirectory = resolve(applicationRoot, "chrome-extension/assets/icons");
const outputDirectory = cliArguments.length ? resolve(cliArguments[1]) : sourceDirectory;
const stagingDirectory = await mkdtemp(join(tmpdir(), "web-translate-icons-"));
const sizes = [16, 32, 48, 128];
const pngSignature = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);
const tileColors = ["#2563EB", "#60A5FA", "#93C5FD", "#3B82F6"];

// SVG 和 PNG 共用四个圆角方块，避免平台 SVG 解码器差异和额外构建依赖。
function createArtwork(small = false) {
	const positions = small ? [1, 9] : [6, 35];
	return {
		viewSize: small ? 16 : 64,
		tiles: tileColors.map((color, index) => ({
			x: positions[index % 2],
			y: positions[Math.floor(index / 2)],
			width: small ? 6 : 23,
			radius: small ? 1.5 : 6,
			color,
		})),
	};
}

function renderSvg(size) {
	const { viewSize, tiles } = createArtwork(size === 16);
	const rectangles = tiles.map(({ x, y, width, radius, color }) =>
		`  <rect x="${x}" y="${y}" width="${width}" height="${width}" rx="${radius}" fill="${color}"/>`,
	);
	return [
		`<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${viewSize} ${viewSize}" fill="none">`,
		"  <!-- Generated by scripts/export-icons.mjs. -->",
		...rectangles,
		"</svg>",
		"",
	].join("\n");
}

function renderPng(size) {
	const { viewSize, tiles } = createArtwork(size === 16);
	const scale = size / viewSize;
	// 每行首字节是 PNG 的过滤类型；剩余字节是透明背景上的 RGBA 像素。
	const rowSize = 1 + size * 4;
	const pixels = Buffer.alloc(rowSize * size);
	for (const tile of tiles) {
		paintTile(pixels, rowSize, {
			x: tile.x * scale,
			y: tile.y * scale,
			width: tile.width * scale,
			radius: tile.radius * scale,
			color: [1, 3, 5].map((offset) => Number.parseInt(tile.color.slice(offset, offset + 2), 16)),
		});
	}
	const header = Buffer.alloc(13);
	header.writeUInt32BE(size, 0);
	header.writeUInt32BE(size, 4);
	header[8] = 8; // 每个颜色通道 8 位。
	header[9] = 6; // RGBA。
	return Buffer.concat([
		pngSignature,
		pngChunk("IHDR", header),
		pngChunk("IDAT", deflateSync(pixels)),
		pngChunk("IEND", Buffer.alloc(0)),
	]);
}

function paintTile(pixels, rowSize, tile) {
	const samples = 4;
	for (let y = Math.floor(tile.y); y < Math.ceil(tile.y + tile.width); y += 1) {
		for (let x = Math.floor(tile.x); x < Math.ceil(tile.x + tile.width); x += 1) {
			let coverage = 0;
			// 子像素覆盖率让小尺寸圆角平滑，透明边缘保留原始颜色。
			for (let sampleY = 0; sampleY < samples; sampleY += 1) {
				for (let sampleX = 0; sampleX < samples; sampleX += 1) {
					const px = x + (sampleX + 0.5) / samples;
					const py = y + (sampleY + 0.5) / samples;
					if (containsPoint(tile, px, py)) coverage += 1;
				}
			}
			if (coverage === 0) continue;
			const offset = y * rowSize + 1 + x * 4;
			pixels.set(tile.color, offset);
			pixels[offset + 3] = Math.round(255 * coverage / (samples * samples));
		}
	}
}

function containsPoint(tile, x, y) {
	if (x < tile.x || y < tile.y || x >= tile.x + tile.width || y >= tile.y + tile.width) {
		return false;
	}
	const centerX = Math.max(tile.x + tile.radius, Math.min(x, tile.x + tile.width - tile.radius));
	const centerY = Math.max(tile.y + tile.radius, Math.min(y, tile.y + tile.width - tile.radius));
	return (x - centerX) ** 2 + (y - centerY) ** 2 <= tile.radius ** 2;
}

function pngChunk(type, data) {
	const chunk = Buffer.alloc(data.length + 12);
	chunk.writeUInt32BE(data.length, 0);
	chunk.write(type, 4, 4, "ascii");
	data.copy(chunk, 8);
	chunk.writeUInt32BE(crc32(chunk.subarray(4, data.length + 8)), data.length + 8);
	return chunk;
}

async function exportIcon(size) {
	const output = join(stagingDirectory, `icon-${size}.png`);
	await writeFile(output, renderPng(size));

	const png = await readFile(output);
	if (png.length < 24 || !png.subarray(0, 8).equals(pngSignature)) {
		throw new Error(`Icon export did not produce a PNG for icon-${size}.png.`);
	}
	if (png.readUInt32BE(16) !== size || png.readUInt32BE(20) !== size) {
		throw new Error(`Icon export produced incorrect dimensions for icon-${size}.png.`);
	}
}

try {
	// Validate every rendered size before replacing any checked-in asset.
	for (const size of sizes) {
		await exportIcon(size);
	}
	await writeFile(join(stagingDirectory, "icon.svg"), renderSvg(128));
	await writeFile(join(stagingDirectory, "icon-small.svg"), renderSvg(16));
	await mkdir(outputDirectory, { recursive: true });
	for (const filename of ["icon.svg", "icon-small.svg", ...sizes.map((size) => `icon-${size}.png`)]) {
		await copyFile(join(stagingDirectory, filename), join(outputDirectory, filename));
	}
	console.log(`Generated SVG and 16, 32, 48 and 128 px PNG icons in ${outputDirectory}.`);
} finally {
	await rm(stagingDirectory, { recursive: true, force: true });
}
