import { copyFile, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { crc32, deflateSync } from "node:zlib";
import { ACTION_ICON_SIZES, getActionIconPaths, LOADING_ICON_STEPS } from "../chrome-extension/background/action-icon-paths.js";

const cliArguments = process.argv.slice(2);
if (cliArguments.length !== 0 && (cliArguments.length !== 2 || cliArguments[0] !== "--output-dir")) {
	throw new Error("Usage: node scripts/export-icons.mjs [--output-dir <directory>]");
}
const applicationRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourceDirectory = resolve(applicationRoot, "chrome-extension/assets/icons");
const outputDirectory = cliArguments.length ? resolve(cliArguments[1]) : sourceDirectory;
const stagingDirectory = await mkdtemp(join(tmpdir(), "web-translate-icons-"));
const sizes = [16, 32, 48, 128];
const pngSignature = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);
const viewSize = 64;
const blue = "#2563EB";
// 按绘制顺序排列：蓝色底、原文卡片、译文卡片。SVG 与 PNG 共用同一份几何定义。
// 文本线条在 16px 下恰好为 1px，避免把细小字符塞进图标。
const artwork = [
	{ x: 2, y: 2, width: 60, height: 60, radius: 16, color: blue },
	{ x: 12, y: 12, width: 30, height: 24, radius: 6, color: "#93C5FD" },
	{ x: 18, y: 20, width: 18, height: 4, radius: 2, color: "#FFFFFF" },
	{ x: 22, y: 28, width: 30, height: 24, radius: 6, color: "#FFFFFF" },
	{ x: 28, y: 36, width: 18, height: 4, radius: 2, color: blue },
	{ x: 28, y: 44, width: 10, height: 4, radius: 2, color: blue },
];

function renderSvg(size) {
	const rectangles = artwork.map(({ x, y, width, height, radius, color }) =>
		`  <rect x="${x}" y="${y}" width="${width}" height="${height}" rx="${radius}" fill="${color}"/>`,
	);
	return [
		`<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${viewSize} ${viewSize}" fill="none">`,
		"  <!-- Generated by scripts/export-icons.mjs. -->",
		"  <title>中英双语翻译</title>",
		...rectangles,
		"</svg>",
		"",
	].join("\n");
}

function renderPng(size, loadingStep = null) {
	const scale = size / viewSize;
	// 每行首字节是 PNG 的过滤类型；剩余字节是透明背景上的 RGBA 像素。
	const rowSize = 1 + size * 4;
	const pixels = Buffer.alloc(rowSize * size);
	for (const shape of loadingStep === null ? artwork : [artwork[0]]) {
		const rectangle = {
			x: shape.x * scale,
			y: shape.y * scale,
			width: shape.width * scale,
			height: shape.height * scale,
			radius: shape.radius * scale,
		};
		const color = [1, 3, 5].map((offset) => Number.parseInt(shape.color.slice(offset, offset + 2), 16));
		paintShape(pixels, rowSize, rectangle, color, (x, y) => containsPoint(rectangle, x, y));
	}
	if (loadingStep !== null) paintLoadingRing(pixels, rowSize, size, loadingStep);
	const header = Buffer.alloc(13);
	header.writeUInt32BE(size, 0);
	header.writeUInt32BE(size, 4);
	header[8] = 8; // 每个颜色通道 8 位。
	header[9] = 6; // RGBA。
	return Buffer.concat([
		pngSignature,
		pngChunk("IHDR", header),
		pngChunk("IDAT", deflateSync(pixels)),
		pngChunk("IEND", Buffer.alloc(0)),
	]);
}

function paintLoadingRing(pixels, rowSize, size, step) {
	const scale = size / viewSize;
	const center = size / 2;
	const radius = 18 * scale;
	const halfStroke = 3 * scale;
	const outerRadius = radius + halfStroke;
	const innerRadius = radius - halfStroke;
	const bounds = { x: center - outerRadius, y: center - outerRadius, width: outerRadius * 2, height: outerRadius * 2 };
	const onRing = (x, y) => {
		const distance = (x - center) ** 2 + (y - center) ** 2;
		return distance >= innerRadius ** 2 && distance <= outerRadius ** 2;
	};
	paintShape(pixels, rowSize, bounds, [96, 165, 250], onRing);
	// 起点始终可见；到达完成状态前保留缺口，完成后由绿色勾确认。
	const sweep = ((step + 1) / (LOADING_ICON_STEPS + 1)) * Math.PI * 2;
	const endX = center + radius * Math.sin(sweep);
	const endY = center - radius * Math.cos(sweep);
	paintShape(pixels, rowSize, bounds, [255, 255, 255], (x, y) => {
		const angle = (Math.atan2(y - center, x - center) + Math.PI * 2.5) % (Math.PI * 2);
		const onArc = onRing(x, y) && angle <= sweep;
		const onStart = (x - center) ** 2 + (y - center + radius) ** 2 <= halfStroke ** 2;
		const onEnd = (x - endX) ** 2 + (y - endY) ** 2 <= halfStroke ** 2;
		return onArc || onStart || onEnd;
	});
}

function paintShape(pixels, rowSize, bounds, color, contains) {
	const samples = 4;
	const size = (rowSize - 1) / 4;
	for (let y = Math.max(0, Math.floor(bounds.y)); y < Math.min(size, Math.ceil(bounds.y + bounds.height)); y += 1) {
		for (let x = Math.max(0, Math.floor(bounds.x)); x < Math.min(size, Math.ceil(bounds.x + bounds.width)); x += 1) {
			let coverage = 0;
			// 子像素覆盖率让小尺寸圆角平滑，透明边缘保留原始颜色。
			for (let sampleY = 0; sampleY < samples; sampleY += 1) {
				for (let sampleX = 0; sampleX < samples; sampleX += 1) {
					const px = x + (sampleX + 0.5) / samples;
					const py = y + (sampleY + 0.5) / samples;
					if (contains(px, py)) coverage += 1;
				}
			}
			if (coverage === 0) continue;
			const offset = y * rowSize + 1 + x * 4;
			const alpha = coverage / (samples * samples);
			const remainingAlpha = (pixels[offset + 3] / 255) * (1 - alpha);
			const outputAlpha = alpha + remainingAlpha;
			// 卡片和文本线条覆盖底色时混合边缘，保留已有底色的不透明度。
			for (let channel = 0; channel < 3; channel += 1) {
				pixels[offset + channel] = Math.round(
					(color[channel] * alpha + pixels[offset + channel] * remainingAlpha) / outputAlpha,
				);
			}
			pixels[offset + 3] = Math.round(255 * outputAlpha);
		}
	}
}

function containsPoint(rectangle, x, y) {
	if (x < rectangle.x || y < rectangle.y || x >= rectangle.x + rectangle.width || y >= rectangle.y + rectangle.height) {
		return false;
	}
	const centerX = Math.max(rectangle.x + rectangle.radius, Math.min(x, rectangle.x + rectangle.width - rectangle.radius));
	const centerY = Math.max(rectangle.y + rectangle.radius, Math.min(y, rectangle.y + rectangle.height - rectangle.radius));
	return (x - centerX) ** 2 + (y - centerY) ** 2 <= rectangle.radius ** 2;
}

function pngChunk(type, data) {
	const chunk = Buffer.alloc(data.length + 12);
	chunk.writeUInt32BE(data.length, 0);
	chunk.write(type, 4, 4, "ascii");
	data.copy(chunk, 8);
	chunk.writeUInt32BE(crc32(chunk.subarray(4, data.length + 8)), data.length + 8);
	return chunk;
}

async function exportIcon(size, loadingStep = null) {
	const filename = loadingStep === null ? `icon-${size}.png` : basename(getActionIconPaths(loadingStep)[size]);
	const output = join(stagingDirectory, filename);
	await writeFile(output, renderPng(size, loadingStep));

	const png = await readFile(output);
	if (png.length < 24 || !png.subarray(0, 8).equals(pngSignature)) {
		throw new Error(`Icon export did not produce a PNG for ${filename}.`);
	}
	if (png.readUInt32BE(16) !== size || png.readUInt32BE(20) !== size) {
		throw new Error(`Icon export produced incorrect dimensions for ${filename}.`);
	}
	return filename;
}

try {
	// Validate every rendered size before replacing any checked-in asset.
	const filenames = ["icon.svg", "icon-small.svg"];
	for (const size of sizes) {
		filenames.push(await exportIcon(size));
	}
	for (let step = 0; step < LOADING_ICON_STEPS; step += 1) {
		for (const size of ACTION_ICON_SIZES) filenames.push(await exportIcon(size, step));
	}
	await writeFile(join(stagingDirectory, "icon.svg"), renderSvg(128));
	await writeFile(join(stagingDirectory, "icon-small.svg"), renderSvg(16));
	await mkdir(outputDirectory, { recursive: true });
	for (const filename of filenames) {
		await copyFile(join(stagingDirectory, filename), join(outputDirectory, filename));
	}
	console.log(`Generated brand icons and ${LOADING_ICON_STEPS} toolbar progress steps in ${outputDirectory}.`);
} finally {
	await rm(stagingDirectory, { recursive: true, force: true });
}
