import { copyFile, mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { crc32, deflateSync } from "node:zlib";

const cliArguments = process.argv.slice(2);
if (cliArguments.length !== 0 && (cliArguments.length !== 2 || cliArguments[0] !== "--output-dir")) {
	throw new Error("Usage: node scripts/export-icons.mjs [--output-dir <directory>]");
}
const applicationRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const sourceDirectory = resolve(applicationRoot, "chrome-extension/assets/icons");
const outputDirectory = cliArguments.length ? resolve(cliArguments[1]) : sourceDirectory;
const stagingDirectory = await mkdtemp(join(tmpdir(), "web-translate-icons-"));
const sizes = [16, 32, 48, 128];
const pngSignature = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);
const tileColors = ["#2563EB", "#60A5FA", "#93C5FD", "#3B82F6"];
const tileGlyphs = ["中", "", "", "A"];
// 笔画使用方块内的相对坐标，SVG 与 PNG 共用，不依赖系统字体。
const glyphPaths = {
	中: [
		[[0.18, 0.30], [0.82, 0.30], [0.82, 0.70], [0.18, 0.70], [0.18, 0.30]],
		[[0.50, 0.14], [0.50, 0.86]],
	],
	A: [
		[[0.22, 0.80], [0.50, 0.20], [0.78, 0.80]],
		[[0.33, 0.57], [0.67, 0.57]],
	],
};

// 小图标略微放大语言方块，给“中 / A”的笔画留出清晰的像素间隔。
function createArtwork(small = false) {
	const positions = small ? [1, 9] : [6, 35];
	const tiles = tileColors.map((color, index) => {
		const glyph = tileGlyphs[index];
		const inset = small && glyph ? 0.5 : 0;
		return {
			x: positions[index % 2] - inset,
			y: positions[Math.floor(index / 2)] - inset,
			width: small ? (glyph ? 7 : 6) : 23,
			radius: small ? (glyph ? 2 : 1.5) : 6,
			color,
			glyph,
		};
	});
	return {
		viewSize: small ? 16 : 64,
		tiles,
		strokes: tiles.flatMap((tile) => createGlyphStrokes(tile, small)),
	};
}

function createGlyphStrokes(tile, small) {
	const paths = glyphPaths[tile.glyph];
	if (!paths) return [];
	return paths.map((points) => ({
		strokeWidth: small ? 0.9 : 2.3,
		points: points.map(([x, y]) => [tile.x + x * tile.width, tile.y + y * tile.width]),
	}));
}

function renderSvg(size) {
	const { viewSize, tiles, strokes } = createArtwork(size === 16);
	const rectangles = tiles.map(({ x, y, width, radius, color }) =>
		`  <rect x="${x}" y="${y}" width="${width}" height="${width}" rx="${radius}" fill="${color}"/>`,
	);
	const paths = strokes.map(({ points, strokeWidth }) => {
		const path = points.map(([x, y], index) =>
			`${index === 0 ? "M" : "L"}${Number(x.toFixed(3))} ${Number(y.toFixed(3))}`,
		).join(" ");
		return `  <path d="${path}" stroke="#FFFFFF" stroke-width="${strokeWidth}" stroke-linecap="round" stroke-linejoin="round"/>`;
	});
	return [
		`<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${viewSize} ${viewSize}" fill="none">`,
		"  <!-- Generated by scripts/export-icons.mjs. -->",
		"  <title>中英双语翻译</title>",
		...rectangles,
		...paths,
		"</svg>",
		"",
	].join("\n");
}

function renderPng(size) {
	const { viewSize, tiles, strokes } = createArtwork(size === 16);
	const scale = size / viewSize;
	// 每行首字节是 PNG 的过滤类型；剩余字节是透明背景上的 RGBA 像素。
	const rowSize = 1 + size * 4;
	const pixels = Buffer.alloc(rowSize * size);
	for (const tile of tiles) {
		const rectangle = {
			x: tile.x * scale,
			y: tile.y * scale,
			width: tile.width * scale,
			height: tile.width * scale,
			radius: tile.radius * scale,
		};
		const color = [1, 3, 5].map((offset) => Number.parseInt(tile.color.slice(offset, offset + 2), 16));
		paintShape(pixels, rowSize, rectangle, color, (x, y) => containsPoint(rectangle, x, y));
	}
	paintGlyphs(pixels, rowSize, strokes.map(({ points, strokeWidth }) => ({
		points: points.map(([x, y]) => [x * scale, y * scale]),
		strokeWidth: strokeWidth * scale,
	})));
	const header = Buffer.alloc(13);
	header.writeUInt32BE(size, 0);
	header.writeUInt32BE(size, 4);
	header[8] = 8; // 每个颜色通道 8 位。
	header[9] = 6; // RGBA。
	return Buffer.concat([
		pngSignature,
		pngChunk("IHDR", header),
		pngChunk("IDAT", deflateSync(pixels)),
		pngChunk("IEND", Buffer.alloc(0)),
	]);
}

function paintShape(pixels, rowSize, bounds, color, contains) {
	const samples = 4;
	const size = (rowSize - 1) / 4;
	for (let y = Math.max(0, Math.floor(bounds.y)); y < Math.min(size, Math.ceil(bounds.y + bounds.height)); y += 1) {
		for (let x = Math.max(0, Math.floor(bounds.x)); x < Math.min(size, Math.ceil(bounds.x + bounds.width)); x += 1) {
			let coverage = 0;
			// 子像素覆盖率让小尺寸圆角平滑，透明边缘保留原始颜色。
			for (let sampleY = 0; sampleY < samples; sampleY += 1) {
				for (let sampleX = 0; sampleX < samples; sampleX += 1) {
					const px = x + (sampleX + 0.5) / samples;
					const py = y + (sampleY + 0.5) / samples;
					if (contains(px, py)) coverage += 1;
				}
			}
			if (coverage === 0) continue;
			const offset = y * rowSize + 1 + x * 4;
			const alpha = coverage / (samples * samples);
			const remainingAlpha = (pixels[offset + 3] / 255) * (1 - alpha);
			const outputAlpha = alpha + remainingAlpha;
			// 白色笔画叠在蓝色底上，边缘混合颜色，保持已有底色的不透明度。
			for (let channel = 0; channel < 3; channel += 1) {
				pixels[offset + channel] = Math.round(
					(color[channel] * alpha + pixels[offset + channel] * remainingAlpha) / outputAlpha,
				);
			}
			pixels[offset + 3] = Math.round(255 * outputAlpha);
		}
	}
}

function paintGlyphs(pixels, rowSize, strokes) {
	if (strokes.length === 0) return;
	const points = strokes.flatMap((stroke) => stroke.points);
	const padding = Math.max(...strokes.map((stroke) => stroke.strokeWidth)) / 2;
	const left = Math.min(...points.map(([x]) => x)) - padding;
	const top = Math.min(...points.map(([, y]) => y)) - padding;
	const bounds = {
		x: left,
		y: top,
		width: Math.max(...points.map(([x]) => x)) + padding - left,
		height: Math.max(...points.map(([, y]) => y)) + padding - top,
	};
	paintShape(pixels, rowSize, bounds, [255, 255, 255], (x, y) =>
		strokes.some((stroke) => pointOnStroke(stroke, x, y)),
	);
}

function pointOnStroke({ points, strokeWidth }, x, y) {
	for (let index = 1; index < points.length; index += 1) {
		const [startX, startY] = points[index - 1];
		const [endX, endY] = points[index];
		const dx = endX - startX;
		const dy = endY - startY;
		const lengthSquared = dx ** 2 + dy ** 2;
		const fraction = lengthSquared === 0 ? 0 :
			Math.max(0, Math.min(1, ((x - startX) * dx + (y - startY) * dy) / lengthSquared));
		const distanceSquared = (x - startX - fraction * dx) ** 2 + (y - startY - fraction * dy) ** 2;
		if (distanceSquared <= (strokeWidth / 2) ** 2) return true;
	}
	return false;
}

function containsPoint(tile, x, y) {
	if (x < tile.x || y < tile.y || x >= tile.x + tile.width || y >= tile.y + tile.width) {
		return false;
	}
	const centerX = Math.max(tile.x + tile.radius, Math.min(x, tile.x + tile.width - tile.radius));
	const centerY = Math.max(tile.y + tile.radius, Math.min(y, tile.y + tile.width - tile.radius));
	return (x - centerX) ** 2 + (y - centerY) ** 2 <= tile.radius ** 2;
}

function pngChunk(type, data) {
	const chunk = Buffer.alloc(data.length + 12);
	chunk.writeUInt32BE(data.length, 0);
	chunk.write(type, 4, 4, "ascii");
	data.copy(chunk, 8);
	chunk.writeUInt32BE(crc32(chunk.subarray(4, data.length + 8)), data.length + 8);
	return chunk;
}

async function exportIcon(size) {
	const output = join(stagingDirectory, `icon-${size}.png`);
	await writeFile(output, renderPng(size));

	const png = await readFile(output);
	if (png.length < 24 || !png.subarray(0, 8).equals(pngSignature)) {
		throw new Error(`Icon export did not produce a PNG for icon-${size}.png.`);
	}
	if (png.readUInt32BE(16) !== size || png.readUInt32BE(20) !== size) {
		throw new Error(`Icon export produced incorrect dimensions for icon-${size}.png.`);
	}
}

try {
	// Validate every rendered size before replacing any checked-in asset.
	for (const size of sizes) {
		await exportIcon(size);
	}
	await writeFile(join(stagingDirectory, "icon.svg"), renderSvg(128));
	await writeFile(join(stagingDirectory, "icon-small.svg"), renderSvg(16));
	await mkdir(outputDirectory, { recursive: true });
	for (const filename of ["icon.svg", "icon-small.svg", ...sizes.map((size) => `icon-${size}.png`)]) {
		await copyFile(join(stagingDirectory, filename), join(outputDirectory, filename));
	}
	console.log(`Generated SVG and 16, 32, 48 and 128 px PNG icons in ${outputDirectory}.`);
} finally {
	await rm(stagingDirectory, { recursive: true, force: true });
}
