import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import {
	chooseProvider,
	clickByText,
	createOptionsPageHarness,
	inputValue,
	settle,
	waitFor,
} from "../helpers/options-page-harness.mjs";

const extensionUrl = new URL("../../chrome-extension/", import.meta.url);

async function readExtensionFile(path) {
	return readFile(new URL(path, extensionUrl), "utf8");
}

function getScriptSources(html) {
	return [...html.matchAll(/<script\s+src="([^"]+)"\s+defer><\/script>/gu)].map(
		(match) => match[1],
	);
}

// 设置页必须只加载本地预编译脚本，并遵守 Manifest V3 的安全执行约束。
test("设置页只使用本地预编译资产和安全 CSP", async () => {
	const [html, optionsScript, optionsStyles, coreScript, manifestSource] = await Promise.all([
		readExtensionFile("options/index.html"),
		readExtensionFile("options/options.js"),
		readExtensionFile("options/options.css"),
		readExtensionFile("generated/core.js"),
		readExtensionFile("manifest.json"),
	]);
	const manifest = JSON.parse(manifestSource);
	const scriptSources = getScriptSources(html);
	const extensionPolicy =
		manifest.content_security_policy?.extension_pages ??
		"script-src 'self'; object-src 'self';";

	assert.deepEqual(scriptSources, [
		"../generated/provider-catalog.js",
		"../generated/core.js",
		"options.js",
	]);
	assert.ok(scriptSources.every((source) => !/^(?:https?:)?\/\//u.test(source)));
	assert.match(html, /<div id="app"><\/div>/u);
	assert.doesNotMatch(html, /<script(?!\s+src=)[^>]*>/u);
	assert.equal(manifest.options_ui.page, "options/index.html");
	assert.equal(manifest.options_ui.open_in_tab, true);
	assert.match(optionsScript, /^\/\/ Generated by scripts\/build-options\.mjs/u);
	assert.match(optionsStyles, /^\/\* Generated by scripts\/build-options\.mjs/u);
	assert.match(coreScript, /^\/\/ Generated by scripts\/build-extension-runtime\.mjs/u);
	assert.match(extensionPolicy, /script-src 'self'/u);
	assert.doesNotMatch(extensionPolicy, /unsafe-eval|https?:/u);
	assert.doesNotMatch(optionsScript, /\beval\s*\(|\bnew\s+Function\s*\(|\bimport\s*\(/u);
});

// 首屏关键锚点和唯一连接主操作必须保持稳定，切换服务时不能丢失未保存草稿。
test("首屏契约稳定且 Provider 切换保留草稿", async () => {
	const page = await createOptionsPageHarness();
	try {
		for (const id of [
			"extension-version",
			"settings-form",
			"provider",
			"deepseek-api-key",
			"deepseek-model",
			"target-mode",
			"concurrency",
			"translate-dynamic",
			"test-provider",
			"status",
			"usage",
		]) {
			assert.ok(page.document.getElementById(id), `缺少设置页锚点 #${id}`);
		}
		assert.equal(page.document.querySelectorAll("[data-provider-fields]").length, 1);
		assert.equal(page.document.querySelectorAll(".primary").length, 1);
		assert.equal(page.document.querySelector("#save"), null);
		assert.equal(
			page.document.querySelector("#test-provider").textContent.trim(),
			"保存并测试",
		);
		assert.equal(page.document.querySelector("#cost-protection"), null);
		assert.equal(page.document.querySelectorAll(".provider-paid").length, 3);
		assert.match(page.document.querySelector(".provider-note").textContent, /感谢梁圣/u);
		assert.equal(
			page.document.querySelector(".provider-billing-note").textContent,
			"标有“付费 API”的服务会按用量计费，实际费用以服务商账单为准。",
		);
		assert.equal(page.document.querySelector("#extension-version").textContent, "v0.4.0");
		assert.equal(
			page.document.querySelectorAll("#provider > .provider-grid:first-of-type .provider-choice")
				.length,
			3,
		);
		assert.equal(page.document.querySelector("#provider-more").getAttribute("aria-expanded"), "false");

		await chooseProvider(page.window, page.document, "openai");
		const openAiKey = page.document.querySelector("#openai-api-key");
		inputValue(page.window, openAiKey, "openai-draft-key");
		await chooseProvider(page.window, page.document, "deepseek");
		await chooseProvider(page.window, page.document, "openai");
		assert.equal(page.document.querySelector("#openai-api-key").value, "openai-draft-key");
	} finally {
		page.cleanup();
	}
});

// 折叠后的当前付费服务仍须展示标签，同时不重复生成额外的付费标签。
test("折叠后的 Anthropic 保留付费标签", async () => {
	const page = await createOptionsPageHarness();
	try {
		page.document.querySelector("#provider-more").click();
		await settle();
		await chooseProvider(page.window, page.document, "anthropic");
		page.document.querySelector("#provider-more").click();
		await settle();
		assert.equal(page.document.querySelector("#provider-more").textContent.includes("付费 API"), true);
		assert.equal(page.document.querySelectorAll(".provider-paid").length, 3);
	} finally {
		page.cleanup();
	}
});

// “保存并测试”必须先持久化当前草稿，再测试 Provider，最后刷新用量状态。
test("保存并测试按固定消息顺序执行", async () => {
	const page = await createOptionsPageHarness();
	try {
		await chooseProvider(page.window, page.document, "openai");
		inputValue(page.window, page.document.querySelector("#openai-api-key"), "openai-draft-key");
		page.clearCalls();
		page.document.querySelector("#test-provider").click();
		await waitFor(
			() => page.document.querySelector("#status").textContent.includes("连接成功"),
			"连接测试未完成",
		);

		assert.deepEqual(
			page.calls.map((message) => message.type),
			["SAVE_SETTINGS", "TEST_PROVIDER", "GET_OPTIONS_STATE"],
		);
		assert.equal(page.calls[0].settings.openai.apiKey, "openai-draft-key");
		assert.match(page.document.querySelector(".connected").textContent, /连接可用/u);
	} finally {
		page.cleanup();
	}
});

// 调试视图必须用 textContent 安全展示白名单元数据，并正确维护 Port 心跳、重连和卸载清理。
test("调试事件安全展示并完整管理 Port 生命周期", async () => {
	const page = await createOptionsPageHarness();
	try {
			clickByText(page.document, ".tabs button", "调试");
			await settle();
			const debugToggle = page.document.querySelector("#debug-logging");
			const payloadToggle = page.document.querySelector("#debug-request-payload");
			assert.equal(payloadToggle.disabled, true);
			assert.equal(payloadToggle.checked, false);
			debugToggle.checked = true;
		debugToggle.dispatchEvent(new page.window.Event("change", { bubbles: true }));
		await waitFor(() => page.ports.length === 1, "调试 Port 未连接");
		await waitFor(
			() => page.calls.some((message) => message.type === "SET_DEBUG_LOGGING"),
				"调试开关未保存",
			);
			assert.equal(payloadToggle.disabled, false);
			payloadToggle.checked = true;
			payloadToggle.dispatchEvent(new page.window.Event("change", { bubbles: true }));
			await waitFor(
				() => page.calls.some((message) => message.type === "SET_DEBUG_REQUEST_PAYLOAD"),
				"请求正文开关未独立保存",
			);
			assert.equal(payloadToggle.checked, true);
		assert.equal(page.timers.heartbeatDelay, 20_000);
		page.timers.runHeartbeat();
		assert.deepEqual(page.ports[0].messages, [{ type: "DEBUG_PING" }]);

		page.ports[0].onMessage.emit({
			type: "DEBUG_SNAPSHOT",
			events: [
				{
					seq: 1,
					timestamp: "2026-08-04T08:00:00.000Z",
					eventType: "<img src=x onerror=alert(1)>",
					endpoint: "https://api.example.com/v1/chat?api_key=secret#fragment",
					requestBody: "must-not-render",
				},
				{
					seq: 2,
					timestamp: "2026-08-04T08:00:01.000Z",
					eventType: "sdk.request-start",
					provider: "deepseek",
					requestId: "provider-request-1",
					requestPayload: {
						model: "deepseek-v4-flash",
						max_tokens: 800,
						messages: [{ role: "user", content: "第一行\n第二行网页原文" }],
						thinking: { type: "disabled", secret: "must-not-render" },
						apiKey: "sk-must-not-render",
						headers: { Authorization: "Bearer must-not-render" },
					},
					requestPayloadTruncated: true,
				},
			],
		});
		await settle();
		clickByText(page.document, ".debug-modes button", "全部事件");
		await settle();
		assert.equal(
			page.document.querySelector(".debug-event-name").textContent,
			"<img src=x onerror=alert(1)>",
		);
		assert.equal(page.document.querySelector("#debug-events img"), null);
		assert.match(page.document.querySelector(".debug-event-meta").textContent, /api\.example\.com\/v1\/chat/u);
		const payload = page.document.querySelector('[data-field="requestPayload"] dd');
		assert.match(payload.textContent, /第一行\\n第二行网页原文/u);
		assert.match(payload.textContent, /"max_tokens": 800/u);
		assert.doesNotMatch(
			page.document.querySelector("#debug-events").textContent,
			/api_key=secret|apiKey|Authorization|must-not-render/u,
		);
			assert.match(
				page.document.querySelector(".debug-head > div > p:last-child").textContent,
				/另行授权.*无痕窗口永不记录.*API Key/u,
			);
		page.document.querySelector("#copy-debug-logs").click();
		await settle();
		assert.match(page.copiedText, /api\.example\.com\/v1\/chat/u);
		assert.match(page.copiedText, /第一行\\\\n第二行网页原文/u);
		assert.doesNotMatch(
			page.copiedText,
			/api_key=secret|apiKey|Authorization|must-not-render/u,
		);

		page.ports[0].drop();
		page.timers.runReconnect();
		await settle();
		assert.equal(page.ports.length, 2);
		const activePort = page.ports.at(-1);
		page.unload();
		assert.equal(activePort.disconnected, true);
	} finally {
		page.cleanup();
	}
});
