import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

import {
	createDeferred,
	createPopupPageHarness,
	waitFor,
} from "../helpers/popup-page-harness.mjs";

const extensionUrl = new URL("../../chrome-extension/", import.meta.url);

function popupState(overrides = {}) {
	return {
		ok: true,
		version: "0.4.0",
		providerLabel: "DeepSeek",
		model: "deepseek-v4-flash",
		targetLanguage: "简体中文",
		debugLogging: false,
		configured: true,
		canTranslate: true,
		unavailableReason: "",
		...overrides,
	};
}

function readExtensionFile(path) {
	return readFile(new URL(path, extensionUrl), "utf8");
}

// 验证 Manifest 指向本地 Popup，页面不包含内联或远程代码，生成资产满足 MV3 CSP。
test("Popup 仅加载本地预编译资产", async () => {
	const [manifestSource, html, script, styles] = await Promise.all([
		readExtensionFile("manifest.json"),
		readExtensionFile("popup/index.html"),
		readExtensionFile("popup/popup.js"),
		readExtensionFile("popup/popup.css"),
	]);
	const manifest = JSON.parse(manifestSource);
	const scriptSources = [...html.matchAll(/<script\s+src="([^"]+)"><\/script>/gu)].map(
		(match) => match[1],
	);
	const styleSources = [...html.matchAll(/<link\s+rel="stylesheet"\s+href="([^"]+)"\s*\/?>/gu)].map(
		(match) => match[1],
	);

	assert.equal(manifest.action.default_popup, "popup/index.html");
	assert.deepEqual(scriptSources, ["popup.js"]);
	assert.deepEqual(styleSources, ["popup.css"]);
	assert.ok([...scriptSources, ...styleSources].every((source) => !/^(?:https?:)?\/\//u.test(source)));
	assert.doesNotMatch(html, /<script(?!\s+src=)[^>]*>/u);
	assert.doesNotMatch(html, /\son[a-z]+\s*=|<style[\s>]/iu);
	assert.match(script, /^\/\/ Generated by scripts\/build-popup\.mjs/u);
	assert.match(styles, /^\/\* Generated by scripts\/build-popup\.mjs/u);
	assert.doesNotMatch(script, /\beval\s*\(|\bnew\s+Function\s*\(|\bimport\s*\(/u);
});

// 验证后台状态返回前主操作保持加载态，返回后再一次性填充服务信息并允许点击。
test("Popup 从加载态进入就绪态", async () => {
	const state = createDeferred();
	const page = await createPopupPageHarness({ getPopupState: () => state.promise });
	try {
		const toggle = page.document.querySelector("#toggle-translation");
		assert.equal(toggle.disabled, true);
		assert.match(page.document.querySelector("#popup-status").textContent, /正在读取/u);

		state.resolve(popupState());
		await waitFor(() => !toggle.disabled, "Popup 未离开加载态");
		assert.equal(page.document.querySelector("#extension-version").textContent, "v0.4.0");
		assert.equal(page.document.querySelector("#current-provider").textContent, "DeepSeek");
		assert.equal(page.document.querySelector("#current-model").textContent, "deepseek-v4-flash");
		assert.equal(page.document.querySelector("#target-language").textContent, "简体中文");
		assert.match(toggle.textContent, /翻译 \/ 恢复当前网页/u);
	} finally {
		state.resolve(popupState());
		page.cleanup();
	}
});

// 验证 DeepL 等已配置的无模型服务显示明确说明，不会被误报为尚未配置。
test("Popup 正确展示已配置的无模型服务", async () => {
	const page = await createPopupPageHarness({
		popupState: { providerLabel: "DeepL", model: "", configured: true },
	});
	try {
		const toggle = page.document.querySelector("#toggle-translation");
		await waitFor(() => !toggle.disabled, "无模型服务未进入就绪态");

		assert.equal(page.document.querySelector("#current-provider").textContent, "DeepL");
		assert.equal(page.document.querySelector("#current-model").textContent, "无需选择模型");
		assert.doesNotMatch(page.document.querySelector("#popup-status").textContent, /未配置/u);
		assert.equal(page.document.querySelector("#popup-status").dataset.error, "false");
	} finally {
		page.cleanup();
	}
});

// 验证不可注入页面明确说明原因并始终禁用主操作，不会发送切换消息。
test("Popup 禁用不可翻译页面", async () => {
	const page = await createPopupPageHarness({
		popupState: { canTranslate: false, unavailableReason: "此页面不支持网页翻译" },
	});
	try {
		await waitFor(
			() => page.document.querySelector("#popup-status").textContent.includes("不支持"),
			"Popup 未显示不可用原因",
		);
		const toggle = page.document.querySelector("#toggle-translation");
		assert.equal(toggle.disabled, true);
		assert.equal(page.document.querySelector("#popup-status").dataset.error, "true");
		toggle.click();
		assert.deepEqual(page.calls.map(({ type }) => type), ["GET_POPUP_STATE"]);
	} finally {
		page.cleanup();
	}
});

// 验证初始状态读取失败时保持安全禁用，并把后台错误显示在可访问状态区域。
test("Popup 安全处理初始加载错误", async () => {
	const page = await createPopupPageHarness({
		getPopupState: async () => ({ ok: false, error: "无法读取当前页面" }),
	});
	try {
		await waitFor(
			() => page.document.querySelector("#popup-status").textContent.includes("无法读取"),
			"Popup 未展示初始加载错误",
		);
		assert.equal(page.document.querySelector("#toggle-translation").disabled, true);
		assert.equal(page.document.querySelector("#popup-status").dataset.error, "true");
	} finally {
		page.cleanup();
	}
});

// 验证设置使用专用 Options API，调试入口在新标签打开现有调试页，两者都会关闭 Popup。
test("Popup 打开设置与调试日志入口", async () => {
	const page = await createPopupPageHarness();
	try {
		page.document.querySelector("#open-settings").click();
		await waitFor(() => page.optionsOpenCount === 1, "Popup 未打开设置页");
		page.document.querySelector("#open-debug").click();
		await waitFor(() => page.createdTabs.length === 1, "Popup 未打开调试页");

		assert.deepEqual(page.createdTabs, [
			{ url: "chrome-extension://popup-test/options/index.html#debug" },
		]);
		assert.equal(page.closeCount, 2);
	} finally {
		page.cleanup();
	}
});

// 验证主操作在请求完成前锁定，连续点击只发送一次切换消息并在成功后关闭 Popup。
test("Popup 主操作 busy 状态阻止双击", async () => {
	const toggleResult = createDeferred();
	const page = await createPopupPageHarness({ toggleActiveTab: () => toggleResult.promise });
	try {
		const toggle = page.document.querySelector("#toggle-translation");
		await waitFor(() => !toggle.disabled, "Popup 主操作未就绪");
		toggle.click();
		toggle.click();
		await waitFor(
			() => page.calls.filter(({ type }) => type === "TOGGLE_ACTIVE_TAB").length === 1,
			"Popup 未发送切换消息",
		);
		assert.equal(toggle.disabled, true);
		assert.match(toggle.textContent, /正在处理/u);

		toggleResult.resolve({ ok: true, status: "triggered" });
		await waitFor(() => page.closeCount === 1, "切换成功后 Popup 未关闭");
		assert.deepEqual(page.calls.map(({ type }) => type), ["GET_POPUP_STATE", "TOGGLE_ACTIVE_TAB"]);
	} finally {
		toggleResult.resolve({ ok: true, status: "triggered" });
		page.cleanup();
	}
});

// 验证后台错误以纯文本状态展示，主操作恢复可用且 Popup 不会误关闭。
test("Popup 展示切换错误并恢复操作", async () => {
	const page = await createPopupPageHarness({
		toggleActiveTab: async () => ({ ok: false, error: "模拟后台失败" }),
	});
	try {
		const toggle = page.document.querySelector("#toggle-translation");
		await waitFor(() => !toggle.disabled, "Popup 主操作未就绪");
		toggle.click();
		await waitFor(
			() => page.document.querySelector("#popup-status").textContent.includes("模拟后台失败"),
			"Popup 未展示后台错误",
		);
		assert.equal(page.document.querySelector("#popup-status").dataset.error, "true");
		assert.equal(toggle.disabled, false);
		assert.equal(page.closeCount, 0);
	} finally {
		page.cleanup();
	}
});
